language: objective-c

osx_image: xcode8.2

script:
   travis_retry xcodebuild -project TypeWritingLabel.xcodeproj -scheme TypeWritingLabel test -destination "platform=iOS Simulator,OS=10.1,name=iPhone SE"
